### ISSUE TITLE
Unable to display multiple profiles

### ISSUE THREAD

**Issue by skinless77** [p-bizouard/ShareMyRoster#22]
When I try to visualize a Warhammer 40k roster with for example an Aledari Wave Serpent with a decreasing profile, none of its characteristics are displayed
![Capture d’écran 2022-05-31 151659](https://user-images.githubusercontent.com/49442615/171182488-f65422d3-3e7d-47b6-9843-0ef471e19c14.png)

**Comment by p-bizouard** [comment]
Hi @skinless77, thank you for pointing this out !

I released a fix, but in case this does not work for you, could you please provide me the `.rosz` file used ?
